Reset adam parameters on LR reset, better logging and MovieSampler fix
open-retina/open-retina pull request #66
Opened 2024-11-11 10:19 UTC by thomasZen

- Re-initialize the Adam if the learning rate was changed by using a new class called OptimizerResetCallback
- Refactor MovieSampler and generate shifts from 0 to clip_chunk_size when not enforcing scene boundaries
- Better logging:
   - Log learning rate
   - Log training stats per epoch leading to smoother and easier comparable graphs
   - Log gradient magnitudes
- Change precision=16 to precision="16-mixed" as this is recommended by pytorch lightning

2024-11-11 14:18 UTC, fededagos requested changes
Could you add the lr_monitor as a callback? Everything else looks good, though I also do not know why you changed readout_positive: False in Lara's config.

2024-11-11 14:18 UTC, fededagos commented on configs/example_train_core_readout_low_res.yaml
> +  positive: False
Why? Lara's original config seems to be positive: https://github.com/open-retina/open-retina/blob/c2e60e2bf5189fd8a2491d01247621cc456be20b/openretina/hoefling_2024/configs.py#L8

2024-11-11 14:18 UTC, fededagos commented on openretina/models/core_readout.py
> +    def get_last_lr(self) -> float:
There is an already implemented callback for lightning to do this: https://pytorch-lightning.readthedocs.io/en/1.2.10/api/pytorch_lightning.callbacks.lr_monitor.html Could we use it? Would avoid having to add this manually in the model.

It should also be more robust given that it is a lightning callback to use out of the box. You could maybe add this to the example config directly.

I think you could just copy these lines from one of the configs in the cell-type branch and it should work:
https://github.com/open-retina/open-retina/blob/c4d3f8527af77358055b399aa5ab9b4a0322d083/configs/minimal_session_agnostic_lightning.yaml#L52

2024-11-14 09:09 UTC, thomasZen commented on configs/example_train_core_readout_low_res.yaml
> +  positive: False
Good point, I changed this back.

2024-11-14 09:10 UTC, thomasZen commented on openretina/models/core_readout.py
> +    def get_last_lr(self) -> float:
Nice, I changed the config and got rid of this function

2024-11-14 09:15 UTC, thomasZen commented
I also added the option to use a seed and then set the determistic option in pytorch lightning

2024-11-14 10:37 UTC, fededagos approved these changes
All good :)

2024-11-14 10:40 UTC, merged